Description:
  This temp launches an EC2 instance which enables SSH.
Resources:
  CFNSecGr:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0889a44b331db0194
      InstanceType: t2.micro
      KeyName: first-key-pair
      SecurityGroups:
        - !Ref CFNSecGr
      Tags:
        - Key: Name
          Value: CFNInstance